#ifndef JOINT_2_H
#define JOINT_2_H

#define ROBOT_NAME "robot"
#define JOINT_NAME "joint_2"

#define PID_LOOP_FREQUENCY_HZ 100
#define PID_LOG_FREQUENCY_HZ 10
#define PID_FREQ_ALPHA 0.9f
#define PID_LOOP_TIME_ALPHA 0.9f

#define HOMING_SPEED 0.1f

#define I2C_FREQ_HZ 400000

#define GEAR_RATIO 15.0f

#define ACTUATOR_MAX M_PI
#define ACTUATOR_MIN -M_PI
#define ACTUATOR_MAX_VELOCITY M_PI * 5
#define ACTUATOR_MAX_ACCELERATION M_PI * 5

#define ENDSTOP_PIN GPIO_NUM_8

#define AS5600_I2C_PORT I2C_NUM_0
#define AS5600_I2C_SDA 18
#define AS5600_I2C_SCL 17
#define AS5600_VELOCITY_FILTER_ALPHA 0.1f
#define INVERT_AS5600 true

#define STEPPER_STEP_PIN GPIO_NUM_4
#define STEPPER_DIR_PIN GPIO_NUM_5
#define STEPPER_EN_PIN GPIO_NUM_6
#define STEPPER_STEPS_PER_REVOLUTION 200
#define STEPPER_MICROSTEPS 8
#define INVERT_STEPPER true

#define POSITION_KP 2.0f
#define POSITION_KI 0.0f
#define POSITION_KD 0.0f
#define POSITION_KF 1.0f

#endif // JOINT_2_H